# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a33128a3e7449c15e53840db3fe7dcb0bc8eb6196f72571de9e954d794f5d3711404ecc0e5d63a60157516624f4ab81acfad17a625a77869ae3bbafb8ab1fe3

test:
  secret_key_base: b589e163a8ba3d6eb4a89ceba87cc05753eee439a4eca369ad5eff7cd92f13fc1bac7617a7ffa9757ae42261f7c32a404e59e0f1d00d2232bb998658f9c77c57

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
